<a href="https://colab.research.google.com/github/fatouu50/tickit-database-analysis/blob/main/notebooks/02_pandas_analyse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

users = pd.read_csv("tickit_public_user.txt", sep="|")
venue = pd.read_csv("tickit_public_venue.txt", sep="|")
category = pd.read_csv("tickit_public_category.txt", sep="|")
event = pd.read_csv("tickit_public_event.txt", sep="|")
listing = pd.read_csv("tickit_public_listing.txt", sep="|")
sale = pd.read_csv("tickit_public_sale.txt", sep="|")

In [8]:
venue['venueseats'] = venue['venueseats'].fillna(0)  #remplacer par 0 les valeurs manquantes

Analyse univariée (par table, avant fusion)

In [9]:
print(category["catgroup"].value_counts())

catgroup
Sports      5
Shows       3
Concerts    3
Name: count, dtype: int64

In [10]:
print(category["catdesc"].value_counts())

catdesc
Major League Baseball                         1
National Football League                      1
Musical theatre                               1
All opera and light opera                     1
All symphony, concerto, and choir concerts    1
National Hockey League                        1
National Basketball Association               1
Major League Soccer                           1
All non-musical theatre                       1
All rock and pop music concerts               1
All jazz singers and bands                    1
Name: count, dtype: int64

In [11]:
print(venue["venuestate"].value_counts())

venuestate
NY    52
CA    27
NV    15
TX    11
OH     8
FL     8
PA     7
IL     6
CO     5
MI     5
MO     5
AZ     4
MN     4
MD     4
ON     4
DC     4
MA     4
GA     3
NJ     3
WA     3
TN     3
WI     3
NC     3
IN     2
UT     2
LA     2
AB     2
OK     1
KS     1
BC     1
OR     1
QC     1
SC     1
Name: count, dtype: int64

In [12]:
venue.dtypes

venueid         int64
venuename      object
venuecity      object
venuestate     object
venueseats    float64
dtype: object

In [13]:
print(venue["venuestate"].value_counts())

venuestate
NY    52
CA    27
NV    15
TX    11
OH     8
FL     8
PA     7
IL     6
CO     5
MI     5
MO     5
AZ     4
MN     4
MD     4
ON     4
DC     4
MA     4
GA     3
NJ     3
WA     3
TN     3
WI     3
NC     3
IN     2
UT     2
LA     2
AB     2
OK     1
KS     1
BC     1
OR     1
QC     1
SC     1
Name: count, dtype: int64

In [14]:
venue["venueseats"].describe()

count      205.00000
mean     16162.15122
std      27037.20496
min          0.00000
25%          0.00000
50%          0.00000
75%      40615.00000
max      91704.00000
Name: venueseats, dtype: float64